apiVersion: apps/v1
kind: Deployment
metadata:
  name: vkube-api-deployment
spec:
  selector:
    matchLabels:
      app: vkube-api
  replicas: 3
  template:
    metadata:
      labels:
        app: vkube-api
    spec:
      containers:
        - name: vkube-api
          image: avermak/vkube-hello:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 22000
