apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vkube-hello-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: grpc-vkube
        protocol: GRPC
      hosts:
        - "*"
